site_name: 自修祭 | JSSC
site_description: 科学部 | 探究文化発表会・自修祭用特設ページ
site_author: Sakai
site_url: https://jishukan-science-club.github.io
repo_name: jishukan-science-club
repo_url: https://github.com/jishukan-science-club/jishukan-science-club.github.io
# google_analytics: 自修館中等教育学校

theme:
    name: material
    palette:
        scheme: preference
        primary: indigo
        accent: amber
    font:
        text: Noto Sans
    language: ja
    # logo: img/
    # favicon: img/
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.tabbed
    - footnotes
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
        generic: true
    - meta

nav:
    - ホーム: https://jishukan-science-club.github.io/
    - 部活紹介: https://jishukan-science-club.github.io/club
    - 用具集:
        - 器具集: https://jishukan-science-club.github.io/equip
        - 薬品集: https://jishukan-science-club.github.io/chemi
    - 実験集:
        - https://jishukan-science-club.github.io/lab/
        - 中和滴定: https://jishukan-science-club.github.io/lab/neut
        - 酸化還元反応: https://jishukan-science-club.github.io/lab/redox
        - 可燃性気体燃焼実験: https://jishukan-science-club.github.io/lab/hyex
    - 研究発表: index.md
        - 2020:
            - 2020/index.md
